# Generated by Django 4.2.2 on 2023-09-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_student_highlighted_student_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
