# Generated by Django 4.2.2 on 2023-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_student_highlighted_student_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(default='Title1', max_length=100),
        ),
    ]
