# Generated by Django 4.2.2 on 2023-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linenos',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
