# Generated by Django 4.2.2 on 2023-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_student_linenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
