# Generated by Django 4.2.2 on 2023-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_student_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='style',
            field=models.CharField(default='friendly', max_length=100),
        ),
    ]
